// ── PUBLISHED / SHOWCASE PROJECTS ─────────────────────────────────────────────
// Each entry = one card in the Showcase section.
// To add a new live project: copy an object below, fill in the fields, save.
// Fields: id, name, tagline, description, tags, url, thumbnail (optional), year
window.PUBLISHED_PROJECTS = [
  {
    id: "solo-capoeira",
    name: "Solo Capoeira",
    tagline: "Daily capoeira training app",
    description:
      "A solo training companion for capoeira practitioners — daily movement sequences, drills, and progress tracking built for consistent practice.",
    tags: ["App", "React", "Fitness", "Capoeira"],
    url: "https://solocapoeira.netlify.app/",
    thumbnail: "",
    year: 2026,
  },
  {
    id: "aura-glow",
    name: "Aura Glow",
    tagline: "Product landing page",
    description:
      "A polished e-commerce landing page for the Aura Glow product line — clean design, product showcase, and call-to-action flow.",
    tags: ["Design", "E-commerce", "Landing Page"],
    url: "https://auraglowproduct.netlify.app/",
    thumbnail: "",
    year: 2026,
  },
];

// ── ACTIVE PROJECTS (IN DEVELOPMENT) ──────────────────────────────────────────
window.PROJECTS = [
  {
    name: "Book Digester",
    tier: "Active Project",
    kind: "Universal book intelligence engine",
    thread: null,
    synopsis:
      "A source-grounded Berimbau learning system: web book, source library, curriculum, practice dashboard, and internal project operating system.",
    spec: [
      "Astro content site",
      "BookLayout shell",
      "Search index shards",
      "Ticket data layer",
    ],
    stack: ["Astro", "TypeScript", "Markdown content", "JSON data", "Python tooling", "Static HTML"],
    tools: ["Codex", "VS Code", "Astro CLI", "Python", "Ehimare brand tokens", "Browser QA"],
    innovations: [
      "Reusable Ehimare brand system",
      "Source-to-practice chapter engine",
      "Internal website ticket manager",
    ],
    status: "In development",
    development: {
      rank: 4,
      stage: "Core system build",
      tokenUse: "Use tokens to stabilize localhost, finish the book digestion flow, and close the Astro ticket plan.",
      nextMilestone: "Working full site plus verified source-to-chapter workflow",
    },
    mainLink: {
      label: "Main Page",
      href: "http://localhost:4321/",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Projects/Book%20Digest/project-management/TICKET_TRACKER.md",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Berimbau/",
      path: "C:\\Projects\\Berimbau",
    },
  },
  {
    name: "SKUi",
    tier: "Active Project",
    kind: "Commerce operating system",
    thread: "codex://threads/019d4bef-7240-74c2-acc4-fa6803f913d2",
    synopsis:
      "An inventory sourcing and automation command system for product filtering, supplier intake, buy/no-buy scoring, launch planning, purchase orders, and lifecycle workflows.",
    spec: [
      "Node server",
      "Modular workflow library",
      "Dashboard APIs",
      "Ticket schema docs",
    ],
    stack: ["Node.js", "Express-style server", "JavaScript modules", "CSV utilities", "JSON state", "HTML dashboard"],
    tools: ["Codex", "GitHub", "Node.js", "Supplier upload API", "Recommendation engine", "Purchase order status API"],
    innovations: [
      "Buy/no-buy automation filter",
      "Supplier-to-launch workflow",
      "Integrated internal ticket schema",
    ],
    status: "In development",
    development: {
      rank: 2,
      stage: "Operator console hardening",
      tokenUse: "Use tokens on workflow completion: supplier intake, scoring logic, purchase-order states, and dashboard QA.",
      nextMilestone: "End-to-end sourcing command center ready for repeated use",
    },
    mainLink: {
      label: "Main Page",
      href: "http://localhost:3030/",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Iventory/docs/ticket_schema.md",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Iventory/",
      path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Iventory",
    },
  },
  {
    name: "Economic Development",
    tier: "Active Project",
    kind: "Economic development platform",
    thread: "codex://threads/019e24b3-7606-7412-8c60-e4d909cc3a42",
    synopsis:
      "A College Park economic-development intelligence system built from BTR records, BOOMSS parcels, Airtable workflows, enrichment sources, workplans, and dashboards.",
    spec: [
      "React research hub",
      "Static research hub",
      "Python workplan catalog",
      "CSV operations data",
    ],
    stack: ["React", "Vite", "TypeScript", "Python", "CSV", "Airtable", "ArcGIS/Census/OCPA data"],
    tools: ["Codex", "Airtable", "Census APIs", "ArcGIS REST", "OCPA data", "LoopNet-style enrichment plan"],
    innovations: [
      "62 analysis workplan catalog",
      "Parcel and business enrichment layer",
      "Main Street operating dashboards",
    ],
    status: "In progress",
    development: {
      rank: 5,
      stage: "Research hub consolidation",
      tokenUse: "Use tokens after SKUi/Ginga to tighten the hub, align ticket CSVs, and package the economic-development dashboards.",
      nextMilestone: "Clean civic research hub with current workplan and ticket evidence",
    },
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Projects/BTR/static_research_hub/index.html",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Projects/BTR/College_Park_ED_Vault/Data/Operations/codex_command_center_tickets.csv",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/BTR/",
      path: "C:\\Projects\\BTR",
    },
    resourceLinks: [
      {
        label: "Operations Hub",
        href: "file:///C:/Projects/BTR/static_research_hub/operations/index.html",
      },
      {
        label: "Ticketing System",
        href: "file:///C:/Projects/BTR/static_research_hub/operations/ticketing_system.html",
      },
      {
        label: "Workplan Index",
        href: "file:///C:/Projects/BTR/static_research_hub/workplan/index.html",
      },
      {
        label: "Research Hub",
        href: "file:///C:/Projects/BTR/research-hub/index.html",
      },
      {
        label: "Analysis Hub",
        href: "file:///C:/Projects/BTR/static_research_hub/analysis.html",
      },
      {
        label: "Permits",
        href: "file:///C:/Projects/BTR/static_research_hub/permits/index.html",
      },
      {
        label: "Valuation",
        href: "file:///C:/Projects/BTR/static_research_hub/valuation/index.html",
      },
      {
        label: "QA",
        href: "file:///C:/Projects/BTR/static_research_hub/qa/index.html",
      },
      {
        label: "Ontology Network",
        href: "file:///C:/Projects/BTR/static_research_hub/ontology/network/index.html",
      },
      {
        label: "Ownership Graph",
        href: "file:///C:/Projects/BTR/static_research_hub/ontology/ownership_graph/index.html",
      },
      {
        label: "College Park Vault",
        href: "file:///C:/Projects/BTR/College_Park_ED_Vault/",
      },
      {
        label: "Corridor Portal",
        href: "file:///C:/Projects/BTR/College_Park_ED_Vault/Deliverables/Dashboards/corridor_portal/index.html",
      },
      {
        label: "KPI Dashboard",
        href: "file:///C:/Projects/BTR/College_Park_ED_Vault/Deliverables/Dashboards/A048_Monthly_KPI_Dashboard.html",
      },
      {
        label: "Valuation Module",
        href: "file:///C:/Projects/BTR/Valuation%20Module/static/index.html",
      },
      {
        label: "Evidence Map",
        href: "file:///C:/Projects/BTR/outputs/evidence_maps/integrated_parcel_business_decision_map.html",
      },
      {
        label: "BTR Task Board",
        href: "file:///C:/Projects/BTR/TASKS.md",
      },
      {
        label: "Operating System",
        href: "file:///C:/Projects/BTR/PROJECT_OPERATING_SYSTEM.md",
      },
      {
        label: "A063 — Ownership Intel: The Drive",
        href: "file:///C:/Projects/BTR/static_research_hub/deliverables/A063.html",
      },
      {
        label: "A066 — Business Intelligence Hub",
        href: "file:///C:/Projects/BTR/static_research_hub/deliverables/A066.html",
      },
      {
        label: "A067 — Permit Intelligence Platform",
        href: "file:///C:/Projects/BTR/static_research_hub/deliverables/A067.html",
      },
      {
        label: "A068 — Ontology Insights",
        href: "file:///C:/Projects/BTR/static_research_hub/deliverables/A068.html",
      },
      {
        label: "A069 — Economic Context Intelligence",
        href: "file:///C:/Projects/BTR/static_research_hub/deliverables/A069.html",
      },
    ],
  },
  {
    name: "Urban Analytics Atlas",
    tier: "Active Project",
    kind: "Urban analytics knowledge system",
    thread: null,
    synopsis:
      "A structured urban analytics atlas that organizes geospatial learning, program databases, portfolio material, research workflows, quality checks, and career-facing resources into one local reference system.",
    spec: [
      "Large static atlas page",
      "Geospatial tech stack map",
      "Learning and materials databases",
      "Ticket and evaluation plans",
    ],
    stack: ["HTML", "CSS", "JavaScript", "Markdown", "Vite app", "Local data folders"],
    tools: ["Codex", "VS Code", "Vite", "Browser QA", "Urban analytics datasets", "Geospatial reference material"],
    innovations: [
      "Urban analytics career and research atlas",
      "Geospatial tech stack learning map",
      "Ticket-backed resource center evaluation system",
    ],
    status: "In development",
    development: {
      rank: 9,
      stage: "Atlas consolidation",
      tokenUse: "Use tokens after the tier-one build queue to tighten navigation, ticket visibility, and resource database coverage.",
      nextMilestone: "Current atlas homepage with verified links into learning, research, operations, and ticket plans",
    },
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Projects/Urban/urban-analytics-atlas.html",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Projects/Urban/urban-analytics-ticketing/",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Urban/",
      path: "C:\\Projects\\Urban",
    },
    resourceLinks: [
      {
        label: "Geospatial Tech Stack",
        href: "file:///C:/Projects/Urban/geospatial-tech-stack.html",
      },
      {
        label: "Evaluation Ticket Plan",
        href: "file:///C:/Projects/Urban/EVALUATION-SCORE-4-TICKET-PLAN.md",
      },
      {
        label: "Site Map",
        href: "file:///C:/Projects/Urban/SITE-MAP.md",
      },
      {
        label: "Atlas App",
        href: "file:///C:/Projects/Urban/atlas-app/dist/index.html",
      },
    ],
  },
  {
    name: "Ginga",
    tier: "Active Project",
    kind: "Training web book",
    thread: "codex://threads/019e6ecb-40c9-7213-9de1-92397a55e52a",
    synopsis:
      "A Capoeira movement-tradition training opus modeled after Berimbau, focused on movement, music, source review, workbook flows, and publication readiness.",
    spec: [
      "Astro publication site",
      "Content collections",
      "Review evidence areas",
      "Publication package data",
    ],
    stack: ["Astro", "TypeScript", "Markdown", "JSON", "Static assets", "Node.js"],
    tools: ["Codex", "Astro", "Browser QA", "Source research", "Markdown pipeline"],
    innovations: [
      "Movement-to-music training architecture",
      "Human review packet workflow",
      "Publication readiness dashboard",
    ],
    status: "In progress",
    development: {
      rank: 3,
      stage: "Publication readiness",
      tokenUse: "Use tokens on ticket closure, source review evidence, navigation QA, and publication packaging.",
      nextMilestone: "Capoeira Movement Tradition site ready for review and publishing",
    },
    mainLink: {
      label: "Main Page",
      href: "http://localhost:4322/",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Projects/Capoeira/astro/dist/tickets/index.html",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Capoeira/",
      path: "C:\\Projects\\Capoeira",
    },
  },
  {
    name: "Berimbau",
    tier: "Active Project",
    kind: "Learning instrument",
    thread: "codex://threads/019de782-11be-7802-bb0a-ed46df951e68",
    synopsis:
      "A local open-source study pipeline for digesting African music books into Obsidian-ready chapter mastery notes, source packets, practice ladders, and teaching material.",
    spec: [
      "PDF-to-Markdown pipeline",
      "OCR runbooks",
      "Obsidian vault outputs",
      "Chapter engine folders",
    ],
    stack: ["Python 3.10+", "PyMuPDF", "watchdog", "requests", "Ollama API", "Markdown", "JSON"],
    tools: ["Codex", "Ollama", "Tesseract guidance", "Obsidian", "Mermaid alternatives"],
    innovations: [
      "Domain-aware book digestion",
      "Chapter mastery engine",
      "Source packet to practice translation",
    ],
    status: "In development",
    development: {
      rank: 8,
      stage: "Knowledge pipeline expansion",
      tokenUse: "Use tokens later for OCR backlog, chapter synthesis quality, and Obsidian output polish after smaller sites are closed.",
      nextMilestone: "Stable book-to-notes pipeline with completion tickets reconciled",
    },
    mainLink: {
      label: "Main Page",
      href: "http://127.0.0.1:8765/",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/African_Music_Book_Study/00_PROJECT_CONTROL/41_FULL_PROJECT_COMPLETION_TICKET_PLAN.md",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/African_Music_Book_Study/",
      path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\African_Music_Book_Study",
    },
  },
  {
    name: "Solo Leveling",
    tier: "Active Project",
    kind: "Capoeira training app",
    thread: null,
    synopsis:
      "A mobile-ready solo capoeira training companion — daily movement sequences, drills, PWA install, and progress tracking built for consistent solo practice.",
    spec: [
      "React 19 PWA",
      "Vite build pipeline",
      "Service worker cache",
      "Dist production build",
    ],
    stack: ["React 19", "Vite", "JavaScript", "CSS", "PWA / Service Worker"],
    tools: ["VS Code", "Vite CLI", "Browser QA", "Netlify deploy"],
    innovations: [
      "PWA-installable training companion",
      "Movement sequence engine",
      "Solo practice progression system",
    ],
    status: "In progress",
    development: {
      rank: 1,
      stage: "Near-complete MVP polish",
      tokenUse: "Use tokens first for final QA, ticket burn-down, deployment checks, and public-site polish.",
      nextMilestone: "Published training app moved from active build to completed showcase",
    },
    mainLink: {
      label: "Main Page",
      href: "http://localhost:5173/",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Projects/Solo%20Leveling/tickets.html",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Solo%20Leveling/",
      path: "C:\\Projects\\Solo Leveling",
    },
    resourceLinks: [
      {
        label: "Handbook",
        href: "file:///C:/Projects/Solo%20Leveling/handbook.html",
      },
    ],
  },
  {
    name: "Resume Studio",
    tier: "Active Project",
    kind: "Application command center",
    thread: null,
    synopsis:
      "A local job application tracking and workflow system — application tracker, resume library, Airtable sync, and end-to-end submission workflow.",
    spec: [
      "Static HTML dashboard",
      "Airtable integration layer",
      "Application tracker",
      "Workflow pipeline pages",
    ],
    stack: ["HTML", "CSS", "JavaScript", "Airtable API", "Local static site"],
    tools: ["VS Code", "Airtable", "Browser QA", "Claude Code slash commands"],
    innovations: [
      "Application-to-workflow pipeline",
      "Airtable-linked job tracker",
      "Role-specific resume library",
    ],
    status: "In development",
    development: {
      rank: 6,
      stage: "Workflow integration",
      tokenUse: "Use tokens to verify Airtable sync, application tracker state, resume library flows, and dev page tickets.",
      nextMilestone: "Application command center usable for live job-search operations",
    },
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Projects/Resume%20Studio/index.html",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Projects/Resume%20Studio/dev.html",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Resume%20Studio/",
      path: "C:\\Projects\\Resume Studio",
    },
  },
  {
    name: "Angola Industry",
    tier: "Active Project",
    kind: "Client growth operating system",
    thread: "codex://threads/019d660e-c87a-7183-b4e1-fd2838f70eba",
    synopsis:
      "A Palmares-rooted Angola school growth workspace for Orlando: curriculum ladder, offers, class funnel, retention system, marketing engine, and franchise packaging.",
    spec: [
      "Static local site",
      "Markdown operating vault",
      "Admin page index",
      "Public site package",
    ],
    stack: ["HTML", "CSS", "JavaScript", "Markdown", "Node.js scripts", "Local static output"],
    tools: ["Codex", "VS Code", "OpenCapoeira scraper", "Local site builder", "Browser QA"],
    innovations: [
      "Progression-first acquisition model",
      "Weekly Angola funnel",
      "Executive showcase ticket plan",
    ],
    status: "In development",
    development: {
      rank: 7,
      stage: "Client package assembly",
      tokenUse: "Use tokens after Resume Studio to connect strategy, offers, curriculum, and growth-system pages into a coherent client package.",
      nextMilestone: "Capoeira Palmares growth system packaged for delivery",
    },
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Capoeira/local_site/output/index.html",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Capoeira/local_site/output/pages/00_executive/executive-site-showcase-ticket-plan.html",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Capoeira/",
      path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Capoeira",
    },
  },
  {
    name: "Permt",
    tier: "Active Project",
    kind: "Permitting intelligence platform",
    thread: null,
    synopsis:
      "BTR Vault — 10 live permitting intelligence applications built on 130,832 City of Orlando permit records. Covers corridor vitality scoring, forecast modeling, ownership graph analysis, a REST data API, BI reporting, and spatial intelligence for College Park economic development.",
    spec: [
      "Economic Vitality Intelligence Site (Chart.js, DuckDB)",
      "Corridor Vitality Score Dashboard (Polars, Pandas)",
      "Contractor Database CRUD (localStorage API)",
      "Permit Intelligence Notebook (Marimo, DuckDB)",
      "Permit Volume Forecast (Prophet, Streamlit)",
      "Vault Data Portal — REST API (Datasette)",
      "Evidence.dev BI Report Suite (SvelteKit)",
      "Spatial Intelligence (DuckDB Spatial, Folium)",
      "Ownership Graph — 1,151 nodes 707 edges (NetworkX, Pyvis)",
      "Observable Framework live analytics dashboard",
      "Polars + Parquet pipeline (94% data compression, 23× faster reads)",
    ],
    stack: [
      "Python", "DuckDB", "Polars", "PyArrow / Parquet", "Pandas",
      "Chart.js", "Plotly", "Marimo", "Prophet", "Streamlit",
      "Datasette", "Evidence.dev", "SvelteKit",
      "NetworkX", "Pyvis", "Observable Framework", "HTML5", "JavaScript",
      "DuckDB Spatial", "Folium",
    ],
    tools: [
      "sqlite-utils", "datasette-vega", "datasette-cluster-map",
      "streamlit-folium", "vis.js", "Observable Plot", "DuckDB-WASM",
      "localStorage API", "VS Code", "City of Orlando Open Data",
    ],
    innovations: [
      "130,832 permit records compressed to 4 MB Parquet — 94% smaller, 23× faster reads",
      "Composite vitality score ranking all 13 Orlando Main Street districts",
      "Ownership graph reveals LLC chains, portfolio landlords, and absentee clusters",
      "10 live tools from one unified data vault across 5 different frameworks",
      "Meta Prophet time-series forecast for permit volume and investment through 2028",
    ],
    status: "Needs ticketing",
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Projects/Permt/apps/static/local-site/portfolio.html",
    },
    ticketLink: null,
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Permt/",
      path: "C:\\Projects\\Permt",
    },
  },
  {
    name: "RetroFax Tools",
    tier: "Active Project",
    kind: "Personal tools suite",
    thread: null,
    synopsis:
      "A tools workspace anchored by RetroFax, local form utilities, fax workflows, Cloudflare worker experiments, and reusable service-form modules.",
    spec: [
      "Static tools homepage",
      "Fax workflow utilities",
      "Tree service form module",
      "Cloudflare worker helper",
    ],
    stack: ["HTML", "CSS", "JavaScript", "Python", "Cloudflare Worker", "Markdown"],
    tools: ["VS Code", "Browser QA", "Cloudflare Worker", "Local file workflow", "Python scripts"],
    innovations: [
      "Reusable local service-form tooling",
      "Fax workflow packaging",
      "Small utility workspace for operational experiments",
    ],
    status: "Needs ticketing",
    development: {
      rank: 12,
      stage: "Tool library indexing",
      tokenUse: "Use tokens later to create a ticket tracker, normalize modules, and add a clear index for every tool in the folder.",
      nextMilestone: "Tools homepage with ticketing and stable module links",
    },
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Projects/Tools/index.html",
    },
    ticketLink: null,
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Tools/",
      path: "C:\\Projects\\Tools",
    },
    resourceLinks: [
      {
        label: "Tree Service Form",
        href: "file:///C:/Projects/Tools/Form%20Tool/Tree%20Service%20Form/tree_service_approval.html",
      },
      {
        label: "Task Manager Analyzer",
        href: "file:///C:/Projects/Tools/Task%20Manager%20Analyzer/task_analysis_output/20260710_135813/task_health_report.html",
      },
      {
        label: "Fax CLI README",
        href: "file:///C:/Projects/Tools/fax_cli/README.md",
      },
      {
        label: "Cloudflare Worker",
        href: "file:///C:/Projects/Tools/cloudflare-worker.js",
      },
    ],
  },
  {
    name: "Task Manager Analyzer",
    tier: "Active Project",
    kind: "Workflow risk analyzer",
    thread: null,
    synopsis:
      "A beginner-friendly Python tool for scoring task-manager exports, finding stale or blocked work, flagging overdue tasks, identifying overloaded assignees, and generating project health reports.",
    spec: [
      "CSV / JSON / JSONL task import",
      "Risk scoring engine",
      "CLI and GUI entry points",
      "HTML, CSV, and JSON report outputs",
    ],
    stack: ["Python", "pandas", "Tkinter GUI", "CSV", "JSON", "Static HTML reports"],
    tools: ["VS Code", "Python", "Local batch launcher", "Task export files", "Browser QA"],
    innovations: [
      "Task risk scoring from common export fields",
      "Project health summary reports",
      "Workflow freeze and overload detection",
    ],
    status: "Needs ticketing",
    development: {
      rank: 13,
      stage: "Analyzer packaging",
      tokenUse: "Use tokens later to add a ticket tracker, stable report index, cleaner launch flow, and integrations for live task tools.",
      nextMilestone: "One-click analyzer package with current sample report and ticketing",
    },
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Projects/Tools/Task%20Manager%20Analyzer/task_analysis_output/20260710_135813/task_health_report.html",
    },
    ticketLink: null,
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Tools/Task%20Manager%20Analyzer/",
      path: "C:\\Projects\\Tools\\Task Manager Analyzer",
    },
    resourceLinks: [
      {
        label: "README",
        href: "file:///C:/Projects/Tools/Task%20Manager%20Analyzer/README.md",
      },
      {
        label: "Launcher",
        href: "file:///C:/Projects/Tools/Task%20Manager%20Analyzer/Launch%20Task%20Manager%20Analyzer.bat",
      },
      {
        label: "GUI Script",
        href: "file:///C:/Projects/Tools/Task%20Manager%20Analyzer/task_process_analyzer_gui.py",
      },
      {
        label: "CLI Script",
        href: "file:///C:/Projects/Tools/Task%20Manager%20Analyzer/task_process_analyzer.py",
      },
      {
        label: "Sample Tasks",
        href: "file:///C:/Projects/Tools/Task%20Manager%20Analyzer/sample_tasks.csv",
      },
      {
        label: "Latest Summary",
        href: "file:///C:/Projects/Tools/Task%20Manager%20Analyzer/task_analysis_output/20260710_135813/analysis_summary.json",
      },
    ],
  },
  {
    name: "Cook Book",
    tier: "Active Project",
    kind: "Culinary web book",
    thread: null,
    synopsis:
      "Soup Africa — Nigeria Edition: a web-native Nigerian cookbook with soups, swallows, sides, regional food notes, culture pages, manuscript pipeline, and print-ready book files.",
    spec: [
      "Web book site",
      "Recipe content collections",
      "Print-ready manuscript",
      "Source and culture pages",
    ],
    stack: ["HTML", "CSS", "JavaScript", "Markdown", "Static web book"],
    tools: ["VS Code", "Browser QA", "Manuscript pipeline", "Publish workflow"],
    innovations: [
      "Nigeria-specific recipe taxonomy",
      "Web-to-print book pipeline",
      "Regional food culture documentation",
    ],
    status: "In development",
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Projects/Cook%20Book/webbook/index.html",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Projects/Cook%20Book/webbook/tracker.html",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Cook%20Book/",
      path: "C:\\Projects\\Cook Book",
    },
    resourceLinks: [
      {
        label: "Soups",
        href: "file:///C:/Projects/Cook%20Book/webbook/soups.html",
      },
      {
        label: "Swallows",
        href: "file:///C:/Projects/Cook%20Book/webbook/swallows.html",
      },
      {
        label: "Regions",
        href: "file:///C:/Projects/Cook%20Book/webbook/regions.html",
      },
      {
        label: "Publish",
        href: "file:///C:/Projects/Cook%20Book/webbook/publish.html",
      },
      {
        label: "Print Book",
        href: "file:///C:/Projects/Cook%20Book/publish/1000_plus_nigerian_soup_recipes_print.html",
      },
    ],
  },
  {
    name: "Black River",
    tier: "Active Project",
    kind: "Personal command center",
    thread: null,
    synopsis:
      "BlackRiver Command Center — a personal strategic operating system with today dashboard, wealth engine, 20-year vision, career roadmap, water index, AI sync framework, and CRUD-driven decision tracking.",
    spec: [
      "Static command center dashboard",
      "CRUD-driven data layer",
      "Node.js local server",
      "AI sync framework",
    ],
    stack: ["HTML", "CSS", "JavaScript", "Node.js", "JSON data", "CRUD operations"],
    tools: ["VS Code", "Node.js", "Browser QA", "Local server"],
    innovations: [
      "20-year vision operating layer",
      "Wealth engine dashboard",
      "AI-synced daily decision tracking",
    ],
    status: "In progress",
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Projects/Black%20river/Command_Center/index.html",
    },
    ticketLink: {
      label: "Ticketing",
      href: "file:///C:/Projects/Black%20river/Command_Center/ticket-crud.html",
    },
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Black%20river/Command_Center/",
      path: "C:\\Projects\\Black river\\Command_Center",
    },
    resourceLinks: [
      {
        label: "Weekly Review",
        href: "file:///C:/Projects/Black%20river/Command_Center/weekly-review.html",
      },
      {
        label: "Water Index",
        href: "file:///C:/Projects/Black%20river/Command_Center/water-index.html",
      },
      {
        label: "AI Sync",
        href: "file:///C:/Projects/Black%20river/Command_Center/ai.html",
      },
      {
        label: "Intake",
        href: "file:///C:/Projects/Black%20river/Command_Center/intake.html",
      },
      {
        label: "Vault Tickets",
        href: "file:///C:/Projects/Black%20river/BlackRiver_Vault/04-PROJECTS/BlackRiver%20Development%20OS/tickets/TICKET_INDEX.md",
      },
    ],
  },
  {
    name: "Insurance",
    tier: "Active Project",
    kind: "Client quote management tool",
    thread: null,
    synopsis:
      "A static site for managing client insurance quotes — individual client pages, quote comparisons, a full-terms data bank, quote request log, and client summary dashboard. Deployed on GitHub Pages.",
    spec: [
      "Client quote pages (Asher, Birgham, Cider Mill)",
      "Quote Comparison tool",
      "Full Terms Data Bank",
      "Quote Request Log",
      "Client Summary dashboard",
    ],
    stack: ["HTML", "CSS", "JavaScript", "GitHub Pages", "Static site"],
    tools: ["VS Code", "GitHub Pages", "Browser QA"],
    innovations: [
      "Client-facing insurance quote delivery via static site",
      "Structured terms data bank for comparison",
      "Logged quote request history",
    ],
    status: "In development",
    mainLink: {
      label: "Main Page",
      href: "https://ajoiventures.github.io/Insurance/",
    },
    ticketLink: null,
    folderLink: {
      label: "GitHub Repo",
      href: "https://github.com/ajoiventures/Insurance",
      path: "C:\\Projects\\Insurance Quote",
    },
    resourceLinks: [
      {
        label: "Quote Comparison",
        href: "https://ajoiventures.github.io/Insurance/Quote%20Comparison.html",
      },
      {
        label: "Client Summary",
        href: "https://ajoiventures.github.io/Insurance/Client%20Summary.html",
      },
      {
        label: "Full Terms Data Bank",
        href: "https://ajoiventures.github.io/Insurance/Full%20Terms%20Data%20Bank.html",
      },
      {
        label: "Quote Request Log",
        href: "https://ajoiventures.github.io/Insurance/Quote%20Request%20Log.html",
      },
    ],
  },
  {
    name: "Politics",
    tier: "Active Project",
    kind: "Civic political research",
    thread: null,
    synopsis:
      "Civic political research hub — Anna Eskamani for Orlando Mayor full platform commitments tracker. Monitors policy positions, campaign promises, and civic priorities for local Orlando electoral intelligence.",
    spec: [
      "Platform commitments tracker",
      "Policy position database",
      "Orlando mayoral race intelligence",
    ],
    stack: ["HTML", "CSS", "JavaScript", "Static site"],
    tools: ["VS Code", "Browser QA"],
    innovations: [
      "Structured civic commitment tracking",
      "Local Orlando electoral intelligence layer",
    ],
    status: "In development",
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Projects/Politics/anna_eskamani_commitments.html",
    },
    ticketLink: null,
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Politics/",
      path: "C:\\Projects\\Politics",
    },
  },
  {
    name: "Tree Service Form",
    tier: "Active Project",
    kind: "Client service form system",
    thread: null,
    synopsis:
      "A Word of Mouth Tree Service form package for quote evaluation, owner approval, and work authorization using photo-heavy local HTML forms.",
    spec: [
      "Static HTML form pages",
      "Photo card asset set",
      "Python page build helper",
      "Local client approval workflow",
    ],
    stack: ["HTML", "CSS", "JavaScript", "Python", "Local image assets"],
    tools: ["VS Code", "Python", "Browser QA", "Local file workflow"],
    innovations: [
      "Photo-supported quote review",
      "Owner approval form package",
      "Field-service authorization workflow",
    ],
    status: "Needs ticketing",
    development: {
      rank: 11,
      stage: "Form package stabilization",
      tokenUse: "Use tokens after higher-priority projects to build a ticket tracker, validate all form states, and package the three form pages as one client workflow.",
      nextMilestone: "Tree service form system with ticketing and one clear index page",
    },
    mainLink: {
      label: "Main Page",
      href: "file:///C:/Projects/Tools/Form%20Tool/Tree%20Service%20Form/tree_service_approval.html",
    },
    ticketLink: null,
    folderLink: {
      label: "Main Folder",
      href: "file:///C:/Projects/Tools/Form%20Tool/Tree%20Service%20Form/",
      path: "C:\\Projects\\Tools\\Form Tool\\Tree Service Form",
    },
    resourceLinks: [
      {
        label: "Quote Evaluation",
        href: "file:///C:/Projects/Tools/Form%20Tool/Tree%20Service%20Form/quote_evaluation.html",
      },
      {
        label: "Work Authorization",
        href: "file:///C:/Projects/Tools/Form%20Tool/Tree%20Service%20Form/wom_work_authorization.html",
      },
    ],
  },
];

window.PROJECT_LIBRARY = [
  {
    name: "00 Atlas",
    source: "Codex",
    category: "Knowledge Systems",
    relatedTierOne: "Book Digester",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\00_Atlas",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/00_Atlas/",
  },
  {
    name: "Project Organize",
    source: "Codex",
    category: "Operations",
    relatedTierOne: "Berimbau",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\10_Project Organize - Desktop -ajoiventures",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/10_Project%20Organize%20-%20Desktop%20-ajoiventures/",
  },
  {
    name: "Collaboration",
    source: "Codex",
    category: "Operations",
    relatedTierOne: "Angola Industry",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Collaboration",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Collaboration/",
  },
  {
    name: "EV",
    source: "Codex",
    category: "Commerce And Mobility",
    relatedTierOne: "SKUi",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\ev",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/ev/",
  },
  {
    name: "Jobs",
    source: "Codex",
    category: "Career And Applications",
    relatedTierOne: "SKUi",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Jobs",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Jobs/",
  },
  {
    name: "Mainstreet",
    source: "Codex",
    category: "Economic Development: Main Street Operations",
    relatedTierOne: "Economic Development",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Mainstreet",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Mainstreet/",
  },
  {
    name: "Mstreet Projects",
    source: "Codex",
    category: "Economic Development: Main Street Operations",
    relatedTierOne: "Economic Development",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Mstreet Projects",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Mstreet%20Projects/",
  },
  {
    name: "Organize",
    source: "Codex",
    category: "Operations",
    relatedTierOne: "Berimbau",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Organize",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Organize/",
  },
  {
    name: "Project Booms",
    source: "Codex",
    category: "Economic Development: BOOMSS And Business Intelligence",
    relatedTierOne: "Economic Development",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Project Booms",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Project%20Booms/",
  },
  {
    name: "Project Grants",
    source: "Codex",
    category: "Economic Development: Grants And Funding",
    relatedTierOne: "Economic Development",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Project Grants",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Project%20Grants/",
  },
  {
    name: "Project Kerala",
    source: "Codex",
    category: "Research And Place",
    relatedTierOne: "Book Digester",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Project Kerala",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Project%20Kerala/",
  },
  {
    name: "Project Leadership Pipeline",
    source: "Codex",
    category: "Learning And Leadership",
    relatedTierOne: "Ginga",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Project Leadership Pipeline",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Project%20Leadership%20Pipeline/",
  },
  {
    name: "Project Marketplace",
    source: "Codex",
    category: "Commerce And Mobility",
    relatedTierOne: "SKUi",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Project Marketplace",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Project%20Marketplace/",
  },
  {
    name: "Project OPUS",
    source: "Codex",
    category: "Economic Development: Strategy And Implementation",
    relatedTierOne: "Economic Development",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Project OPUS",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Project%20OPUS/",
  },
  {
    name: "Project Resume",
    source: "Codex",
    category: "Career And Applications",
    relatedTierOne: "SKUi",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\project Resume",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/project%20Resume/",
  },
  {
    name: "Rally Mainstreet",
    source: "Codex",
    category: "Economic Development: Campaigns And Mobilization",
    relatedTierOne: "Economic Development",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Rally_Mainstreet",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Rally_Mainstreet/",
  },
  {
    name: "Reframing",
    source: "Codex",
    category: "Knowledge Systems",
    relatedTierOne: "Book Digester",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Reframing",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Reframing/",
  },
  {
    name: "Shoes",
    source: "Codex",
    category: "Commerce And Mobility",
    relatedTierOne: "SKUi",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Shoes",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Shoes/",
  },
  {
    name: "Supply Chain",
    source: "Codex",
    category: "Commerce And Mobility",
    relatedTierOne: "SKUi",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Codex\\Supply Chain",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Codex/Supply%20Chain/",
  },
  {
    name: "Cowork",
    source: "Claude",
    category: "Operations",
    relatedTierOne: "Angola Industry",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Claude\\Cowork",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Claude/Cowork/",
  },
  {
    name: "Mainstreet",
    source: "Claude",
    category: "Economic Development: Main Street Operations",
    relatedTierOne: "Economic Development",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Claude\\Mainstreet",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Claude/Mainstreet/",
  },
  {
    name: "Project Magnus",
    source: "Claude",
    category: "Research And Place",
    relatedTierOne: "Book Digester",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Claude\\Project Magnus",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Claude/Project%20Magnus/",
  },
  {
    name: "Project Resume",
    source: "Claude",
    category: "Career And Applications",
    relatedTierOne: "SKUi",
    path: "C:\\Users\\Paul Irumudomon\\OneDrive\\Desktop\\Claude\\Project Resume",
    href: "file:///C:/Users/Paul%20Irumudomon/OneDrive/Desktop/Claude/Project%20Resume/",
  },
  {
    name: "Urban Analytics Atlas",
    source: "Projects",
    category: "Knowledge Systems",
    relatedTierOne: "Urban Analytics Atlas",
    path: "C:\\Projects\\Urban",
    href: "file:///C:/Projects/Urban/urban-analytics-atlas.html",
  },
  {
    name: "Urban Analytics Ticketing",
    source: "Projects",
    category: "Operations",
    relatedTierOne: "Urban Analytics Atlas",
    path: "C:\\Projects\\Urban\\urban-analytics-ticketing",
    href: "file:///C:/Projects/Urban/urban-analytics-ticketing/",
  },
  {
    name: "RetroFax Tools",
    source: "Projects",
    category: "Operations",
    relatedTierOne: "RetroFax Tools",
    path: "C:\\Projects\\Tools",
    href: "file:///C:/Projects/Tools/index.html",
  },
  {
    name: "Tree Service Form",
    source: "Projects",
    category: "Operations",
    relatedTierOne: "RetroFax Tools",
    path: "C:\\Projects\\Tools\\Form Tool\\Tree Service Form",
    href: "file:///C:/Projects/Tools/Form%20Tool/Tree%20Service%20Form/tree_service_approval.html",
  },
  {
    name: "Task Manager Analyzer",
    source: "Projects",
    category: "Operations",
    relatedTierOne: "Task Manager Analyzer",
    path: "C:\\Projects\\Tools\\Task Manager Analyzer",
    href: "file:///C:/Projects/Tools/Task%20Manager%20Analyzer/task_analysis_output/20260710_135813/task_health_report.html",
  },
  {
    name: "BTR Static Research Hub",
    source: "Projects",
    category: "Economic Development: Research Hub",
    relatedTierOne: "Economic Development",
    path: "C:\\Projects\\BTR\\static_research_hub",
    href: "file:///C:/Projects/BTR/static_research_hub/index.html",
  },
  {
    name: "BTR Operations Module",
    source: "Projects",
    category: "Economic Development: Operations And Governance",
    relatedTierOne: "Economic Development",
    path: "C:\\Projects\\BTR\\static_research_hub\\operations",
    href: "file:///C:/Projects/BTR/static_research_hub/operations/index.html",
  },
  {
    name: "BTR Workplan Module",
    source: "Projects",
    category: "Economic Development: Workplans And Deliverables",
    relatedTierOne: "Economic Development",
    path: "C:\\Projects\\BTR\\docs\\workplans",
    href: "file:///C:/Projects/BTR/static_research_hub/workplan/index.html",
  },
  {
    name: "BTR Permits Module",
    source: "Projects",
    category: "Economic Development: BOOMSS And Business Intelligence",
    relatedTierOne: "Economic Development",
    path: "C:\\Projects\\BTR\\static_research_hub\\permits",
    href: "file:///C:/Projects/BTR/static_research_hub/permits/index.html",
  },
  {
    name: "BTR Valuation Module",
    source: "Projects",
    category: "Economic Development: Valuation And Investment",
    relatedTierOne: "Economic Development",
    path: "C:\\Projects\\BTR\\Valuation Module",
    href: "file:///C:/Projects/BTR/Valuation%20Module/static/index.html",
  },
  {
    name: "BTR Ontology Module",
    source: "Projects",
    category: "Economic Development: Ontology And Ownership",
    relatedTierOne: "Economic Development",
    path: "C:\\Projects\\BTR\\Ontology",
    href: "file:///C:/Projects/BTR/static_research_hub/ontology/network/index.html",
  },
  {
    name: "BTR Evidence Maps",
    source: "Projects",
    category: "Economic Development: Maps And Spatial Intelligence",
    relatedTierOne: "Economic Development",
    path: "C:\\Projects\\BTR\\outputs\\evidence_maps",
    href: "file:///C:/Projects/BTR/outputs/evidence_maps/integrated_parcel_business_decision_map.html",
  },
  {
    name: "College Park ED Vault",
    source: "Projects",
    category: "Economic Development: Main Street Operations",
    relatedTierOne: "Economic Development",
    path: "C:\\Projects\\BTR\\College_Park_ED_Vault",
    href: "file:///C:/Projects/BTR/College_Park_ED_Vault/",
  },
  {
    name: "BTR Web Deliverables",
    source: "Projects",
    category: "Economic Development: Workplans And Deliverables",
    relatedTierOne: "Economic Development",
    path: "C:\\Projects\\BTR\\web\\public\\deliverables",
    href: "file:///C:/Projects/BTR/web/public/deliverables/index.html",
  },
  {
    name: "BTR Data And Scripts",
    source: "Projects",
    category: "Economic Development: Data Engineering",
    relatedTierOne: "Economic Development",
    path: "C:\\Projects\\BTR\\data",
    href: "file:///C:/Projects/BTR/data/outputs/external_service_registry.json",
  },
  {
    name: "Black River Command Center",
    source: "Projects",
    category: "Operations",
    relatedTierOne: "Black River",
    path: "C:\\Projects\\Black river\\Command_Center",
    href: "file:///C:/Projects/Black%20river/Command_Center/index.html",
  },
  {
    name: "Cook Book Webbook",
    source: "Projects",
    category: "Knowledge Systems",
    relatedTierOne: "Cook Book",
    path: "C:\\Projects\\Cook Book\\webbook",
    href: "file:///C:/Projects/Cook%20Book/webbook/index.html",
  },
];
